name = Zeek's World
description = A kid-friendly creative voxel game with an AI cat companion. Explore your real neighborhood in blocks!
first_mod = zw_blocks
allowed_mapgens = singlenode
disallowed_mapgen_settings = mgflat_np_terrain,mgflat_np_cave1
author = xnet
title = Zeek's World
